service: hello
app: serverless-test-app
plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-wsgi
custom:
  stage: dev
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  memorySize: 256
  versionFunctions: false
  timeout: 30
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
    - application/pdf
    - multipart/form-data

package:
  exclude:
    - myvirtualenv/** # virtualenv
    - .virtualenv/** # virtualenv
    - node_modules/** # virtualenv
    - build/**
    - .serverless/**

functions:
  hello:
    handler: wsgi_handler.handler
    events:
      - http:
          path: hello
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            cacheControl: 'max-age=86400, s-maxage=86400, proxy-revalidate'
